### ISSUE TITLE
FAKE NUnit can't find nunit-console

### ISSUE THREAD

**Issue by simra** [fslaborg/FSharp.Charting#140]
Creating an issue for tracking.  We have some bitrot and the Fake NUnit reference can't find the test runner.  I suspect we either need to upgrade to NUnit3, or restrict the maximum NUnit version to something Fake can handle in paket.dependencies. I'll ask some questions on SO.  cc @dsyme @tpetricek @forki in case you have any suggestions.

  1) System.Exception: Start of process c:\GitHub\FSharp.Charting_20180310\tools\Nunit\nunit-console.exe failed. The system cannot find the file specified
   at Fake.ProcessHelper.ExecProcessWithLambdas@91-16.Invoke(String message) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 91
   at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 91
   at Fake.NUnitSequential.NUnit(FSharpFunc`2 setParams, IEnumerable`1 assemblies) in C:\code\fake\src\app\FakeLib\UnitTest\NUnit\Sequential.fs:line 26
   at FSI_0005.Build.clo@113-10.Invoke(Unit _arg6)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626

**Comment by simra** [comment]
Here is some info from paket.lock:
 FAKE (4.61.3) - framework: net40, net45, net461
NUnit (3.7.1) - framework: net40, net45, net461
    NUnit.ConsoleRunner (3.6.1) - framework: net40, net45, net461
NUnit.Runners (3.6.1) - framework: net40, net45, net461
      NUnit.ConsoleRunner (>= 3.6.1) - framework: net40, net45, net461
